# Site settings
title: "Daniel Varga's Cybersecurity Blog"
description: "Exploring hacking techniques, cybersecurity insights, and ethical hacking tutorials."
baseurl: "" # Leave empty if deploying to GitHub Pages root
url: "https://dnlvarga.github.io" # Change this to your actual URL

# Author information
author:
  name: "Daniel Varga"
  email: "your-email@example.com"
  github: "dnlvarga"
  twitter: "your-twitter-handle"

# Theme and appearance
theme: minima # You can change this to another Jekyll theme
show_excerpts: true # Show post summaries

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination settings
paginate: 5 # Number of posts per page
paginate_path: "/page:num/"

# Navigation links
nav_links:
  - name: "Home"
    url: "/"
  - name: "Blog"
    url: "/blog/"
  - name: "About"
    url: "/about/"
  - name: "Contact"
    url: "/contact/"

# Markdown settings
markdown: kramdown
highlighter: rouge # Syntax highlighting for code blocks

# Social media links (for SEO)
social:
  name: "David Smith"
  links:
    - "https://github.com/davidsmith"
    - "https://twitter.com/your-twitter-handle"
    - "https://linkedin.com/in/davidsmith"

# Exclude these files from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
